const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),fs=require("fs"),path=require("path"),http=require("http"),crypto=require("crypto"),multer=require("multer"),{WebSocketServer}=require("ws");
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server}),PORT=process.env.PORT||8080,SECRET=process.env.JWT_SECRET||"change-me";
const DB=path.join(__dirname,"data.json"),UP=path.join(__dirname,"uploads"); if(!fs.existsSync(UP))fs.mkdirSync(UP,{recursive:true}); if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],messages:[]}));
const read=()=>JSON.parse(fs.readFileSync(DB));const write=x=>fs.writeFileSync(DB,JSON.stringify(x));
app.use(cors());app.use(express.json());app.use("/uploads",express.static(UP));const upload=multer({dest:UP,limits:{fileSize:50*1024*1024}});
const sign=u=>jwt.sign({id:u.id,username:u.username},SECRET,{expiresIn:"30d"});
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").replace("Bearer ",""),SECRET);next()}catch{res.status(401).json({error:"unauthorized"})}}
app.get("/health",(q,s)=>s.json({ok:true,name:"ChatMessenger"}));
app.post("/auth/register",async(req,res)=>{const {username,password,name}=req.body||{};if(!username||!password)return res.status(400).json({error:"username/password required"});const d=read();if(d.users.some(u=>u.username===username))return res.status(409).json({error:"username exists"});const u={id:crypto.randomUUID(),username,name:name||username,password:await bcrypt.hash(password,10),online:false,lastSeen:Date.now()};d.users.push(u);write(d);res.json({token:sign(u),user:{id:u.id,username:u.username,name:u.name}})});
app.post("/auth/login",async(req,res)=>{const {username,password}=req.body||{},d=read(),u=d.users.find(x=>x.username===username);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:"invalid login"});u.online=true;u.lastSeen=Date.now();write(d);res.json({token:sign(u),user:{id:u.id,username:u.username,name:u.name}})});
app.get("/users/search",auth,(req,res)=>{const q=String(req.query.q||"").toLowerCase(),d=read();res.json(d.users.filter(u=>u.id!==req.user.id&&(u.username.toLowerCase().includes(q)||u.name.toLowerCase().includes(q))).map(u=>({id:u.id,username:u.username,name:u.name,online:u.online,lastSeen:u.lastSeen})).slice(0,30))});
app.get("/messages/:id",auth,(req,res)=>{const d=read();res.json(d.messages.filter(m=>(m.from===req.user.id&&m.to===req.params.id)||(m.to===req.user.id&&m.from===req.params.id)).slice(-200))});
app.post("/media",auth,upload.single("file"),(req,res)=>{if(!req.file)return res.status(400).json({error:"file required"});res.json({url:"/uploads/"+req.file.filename,name:req.file.originalname,type:req.file.mimetype,size:req.file.size})});
const peers=new Map();
wss.on("connection",(ws,req)=>{try{const t=new URL(req.url,"http://localhost").searchParams.get("token"),u=jwt.verify(t,SECRET);peers.set(u.id,ws);ws.on("close",()=>peers.delete(u.id));ws.on("message",raw=>{try{const x=JSON.parse(raw);if(x.type!=="message"||!x.to)return;const m={id:crypto.randomUUID(),from:u.id,to:x.to,text:x.text||"",kind:x.kind||"text",media:x.media||null,createdAt:Date.now()};const d=read();d.messages.push(m);write(d);const p=peers.get(x.to);if(p&&p.readyState===1)p.send(JSON.stringify({type:"message",message:m}));ws.send(JSON.stringify({type:"message",message:m}))}catch{}})}catch{ws.close()}});
server.listen(PORT,()=>console.log("ChatMessenger server "+PORT));
